/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsa_project_musicplayer;

import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author adamhafiz
 */
public class SpotifyGUI extends javax.swing.JFrame {

    private MyQueue upNextQueue;
    private Stack<String> historyStack;
    private String currentSong = "No Song Playing";
    /**
     * Creates new form SpotifyGUI
     */
    public SpotifyGUI() {
        initComponents();
        upNextQueue = new MyQueue();
        historyStack = new Stack<>();
        
        updateDisplay(); // Show initial state
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        lblCurrent = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQueue = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHistory = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnPlayNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInput.setText("jTextField1");

        lblCurrent.setText("jLabel1");

        txtQueue.setColumns(20);
        txtQueue.setRows(5);
        jScrollPane1.setViewportView(txtQueue);

        txtHistory.setColumns(20);
        txtHistory.setRows(5);
        jScrollPane2.setViewportView(txtHistory);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnPlayNext.setText("Next");
        btnPlayNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayNextActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnAdd)
                        .addGap(39, 39, 39)
                        .addComponent(btnPlayNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCurrent)
                                .addGap(88, 88, 88)
                                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrent))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnPlayNext)
                    .addComponent(btnBack))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String songName = txtInput.getText().trim();
        
        if (songName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a song name!");
            return;
        }

        if (upNextQueue.full()) {
            // RUBRIC: Handling Edge Case (Queue Full)
            JOptionPane.showMessageDialog(this, "Queue is Full! Wait for songs to finish.");
        } else {
            upNextQueue.enqueue(songName);
            txtInput.setText(""); // Clear input
            updateDisplay();
        }
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPlayNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayNextActionPerformed
       
     if (upNextQueue.empty()) {
                // RUBRIC: Handling Edge Case (Queue Empty)
                JOptionPane.showMessageDialog(this, "Up Next is Empty! Add songs first.");
            } else {
                // If a song is currently playing, move it to History Stack first
                if (!currentSong.equals("No Song Playing")) {
                    historyStack.push(currentSong);
                }

                // Get next song from Queue (FIFO)
                currentSong = upNextQueue.dequeue();
                updateDisplay();
            }



        
    }//GEN-LAST:event_btnPlayNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
if (historyStack.isEmpty()) {
            // RUBRIC: Handling Edge Case (Stack Empty)
            JOptionPane.showMessageDialog(this, "No history to go back to!");
        } else {
            // --- FIX START: Save the current song before leaving it! ---
            if (!currentSong.equals("No Song Playing")) {
                if (!upNextQueue.full()) {
                    // Put the song we are leaving back into the Queue so it's not lost
                    upNextQueue.enqueue(currentSong);
                } else {
                    // Optional: Warn user if Queue is full, or just proceed
                    System.out.println("Warning: Queue full, current song lost on Back action.");
                }
            }
            // --- FIX END ---

            // Pop the last song from Stack (LIFO)
            String previousSong = historyStack.pop();
            
            // Put current song back to front of queue (Optional logic, keeps flow smooth)
            // But for simple Back logic, we just play the previous song
            currentSong = previousSong;
            updateDisplay();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    
    private void updateDisplay() {
        lblCurrent.setText("Now Playing: " + currentSong);
        txtQueue.setText(upNextQueue.toString());
        txtHistory.setText(historyStack.toString());    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpotifyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpotifyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpotifyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpotifyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpotifyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlayNext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JTextArea txtHistory;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextArea txtQueue;
    // End of variables declaration//GEN-END:variables
}
